# This is a basic workflow to help you get started with Actions

name: Compile LaTeX

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tectonic
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh
          ./tectonic --version

      - name: Compile LaTeX
        run: |
          ./tectonic aa-demo.tex
