name: Compile LaTeX

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - uses: actions/checkout@v4

        - name: Install tectonic
          run: |
            curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh
            ./tectonic --version

        - name: Compile LaTeX
          run: |
            ./tectonic aa-paper.tex

        - name: Upload resulting PDF
          uses: EndBug/add-and-commit@v9
          with:
            add: '[ "aa-paper.pdf" ]'
            pull: '--rebase --autostash'
